spring:
    application:
        name: admin_service
    datasource:
        url: jdbc:postgresql://localhost:5432/admin-service-db
        username: dev
        password: 98872114
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        properties:
            hibernate:
                '[format_sql]': true